#!/bin/bash
cd $GOPATH/src/github.com/1lann/smarter-hospital/server
go build -o server . || exit
echo "Server built"
cd ../views
go-bindata -nocompress -pkg views -o assets.go `find . -type f -name "*.tmpl"`
echo "Assets packed"
cd script
gopherjs build --tags debug -o ../../server/vendor/js/views.min.js || exit
echo "JS built"
cd ../../server
./server
